DATASET:
  PRETRAINING:
    DATASET: 'kinetics400'
    TRANSFORMATIONS:
      CROP_SIZE: (224,224)
      SCALE_SIZE: (224,224)
      HORIZONTAL_FLIP: True
      RANDOM_GREY: True
      COLOUR_JITTER: True
  FINETUNING:
    TRANSFORMATIONS:
      RESIZE: (224,224)
      CROP_SIZE: (224,224)
MODEL:
  TRUNK: 'resnet18'
  PRETRAINING:
    FC_DIM: 128
  FINETUNING:
    NUM_CLASSES: 101
    DROPOUT: 0
LOSS:
  PRETRAINING:
    ROTATION_WEIGHT: 1
    NCE:
      NEGATIVES: 8192
      TEMPERATURE: 0.07
      MOMENTUM: 0.5
    MINING:
      THRESH_LOW: -1
      THRESH_HIGH: 1
      THRESH_RATE: 5
      MAX_HARD_NEGATIVES_PERCENTAGE: 1 
TRAIN:
  PRETRAINING:
    SAVEDIR: ''
    LEARNING_RATE: 0.03
    DECAY_EPOCHS: (25,)
    DECAY_FACTOR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
    BATCH_SIZE: 100
    EPOCHS: 50
    FRAME_PADDING: 0
  FINETUNING:
    SAVEDIR: ''
    CHECKPOINT: ''
    RESUME: FALSE
    LEARNING_RATE: 0.05
    DECAY_EPOCHS: (375,)
    DECAY_FACTOR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0
    BATCH_SIZE: 100
    EPOCHS: 900
    VAL_FREQ: 3
VISUALISATION:
  TSNE:
    CROP_SIZE: 224
    RESIZE: 224


